//Applications
export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS';
export const LOAD_APPLICATIONS_SUCCESS = 'LOAD_APPLICATIONS_SUCCESS';
export const LOAD_APPLICATIONS_FAILURE = 'LOAD_APPLICATIONS_FAILURE';

//Filters
export const SET_POSITIONS = 'SET_POSITIONS';
export const SET_STATUSES = 'SET_STATUSES';
export const SET_FILTERING_PARAMS = 'SET_FILTERING_PARAMS';
export const RESET_FILTERING_PARAMS = 'RESET_FILTERING_PARAMS';