//Applications
export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS';
export const LOAD_APPLICATIONS_SUCCESS = 'LOAD_APPLICATIONS_SUCCESS';
export const LOAD_APPLICATIONS_FAILURE = 'LOAD_APPLICATIONS_FAILURE';

//Filters
export const SET_POSITIONS = 'SET_POSITIONS';
export const SET_STATUSES = 'SET_STATUSES';
export const SET_FILTER_BY = 'SET_FILTER_BY';
export const SET_ORDER_BY = 'SET_ORDER_BY';
export const RESET_ORDER_BY = 'RESET_ORDER_BY';
export const RESET_FILTER_BY = 'RESET_FILTER_BY';